### ISSUE TITLE
using stUd without an account doesnt work anymore

### ISSUE THREAD

**Issue by milanmic** [matv1/stUd-client#3]
I just tested using stUd without an account. This used to work but does not anymore. 
If I just start entering items when no account exists, the items do not get stored.

**Comment by matv1** [comment]
urgh :( you are right. This is a regression

**Comment by matv1** [comment]
and not an easy one to fix without some major reworking unfortunately. 
I think i shall just change the text at the accountpage to note that one does need to create an account whether using local storage only or a stUd online account.

That does actually make some sense because a local list that some one would already be using, could still become an online list if that person would register those account credentials at studlist.eu

**Comment by matv1** [comment]
fixed
